server.port: 8080
spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:crmdb
    driver-class-name: org.h2.Driver
    username: crm
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

crm.rule.filterSignUpDateTo: 2018-11-01T00:00:00
crm.rule.filterSignUpDateFrom: 2017-12-31T23:59:58
